### ISSUE TITLE
Large image upload

### ISSUE THREAD

**Issue by gkyildirim** [MerlinDMC/smartos-public-dsapi#4]
Hello,

Thank you for sharing this stuff. It looks great and easy to use.

I'd like to ask how to upload large files (45G+). As far as I know curl update is an option but it requires too much memory. 
This is not a perfect issue but I think it woud be clear to ask in this space.

Thanks,

Goktug

**Comment by MerlinDMC** [comment]
You'll have issues on the server-side as well if you run that in a smartos zone.

By default it places uploads in the /tmp directory which is pretty limited by default. You could higher tmpsize to a reasonable value but I guess for 45G it would be better to change the temporary upload directory...
this should do well there (but I currently have no test server here while renovations is going on): cd12700b623e6a8bd0b1128d6dc2d144912933a0

For uploading stuff I switched to httpie (https://github.com/jkbr/httpie) but I did never have to upload such large images.

**Comment by gkyildirim** [comment]
Thanks for the change. It seems to be working, files are being uploaded to /var/tmp instead of /tmp.
However it seems like there is a mistake. I am trying to upload as below but no success so far. I guess I am using "image name" not correctly and upload ends with an error message after a few minutes (after ~13GB upload which is the current size of my win2k8r2.zvol.gz file).

curl -X PUT -u user1:123 -F manifest=@windows.manifest -F winimage=@win2k8r2.zvol.gz http://10.0.50.104:8080/datasets/003cd6b4-e2f8-11e2-ab71-d3f28a2d7815

{
  "code": "InternalError",
  "message": "Cannot read property 'name' of undefined"
}

I confirm that both the manifest and the zvol.gz are uploaded in /var/tmp. Also imgadm avail shows the image and importing ends with an error "imgadm: error (HPE_INVALID_CONSTANT): Parse Error"

After a new try with modifying manifest file (extracted url definition) now the error message is like this and files are uploaded in /var/tmp correctly. This time imgadm avail does not show the image.
{
  "message": "file \"/var/tmp/win2k8r2.zvol.gz \" is missing."
}

I hope these helps. I can also run new tests when available.

**Comment by trentster** [comment]
The upload mechanism is painful I have found you need a huge amount of ram
and you need 1.5x the amount of ram for swap. The correct fix for this is
for Daniel to fix the upload mechanism to something sane that does not
require jumping through hoops and tweaking and reconfiguring the ram and vm
swap etc just to allow upload of a dataset.

This is something he mentioned he would look at sorting out many months
back, until he has a chance to fix it, I fear the process will remain
macgyver'ish and painful.

Daniel perhaps in the interim you can write a Doc for github explaining the
way it currently works and the processes needed to successfully complete an
upload. my 2 cents ;-)

Kind Regards,
**
_Mark Slatem_
